dependencies:
- OpenZeppelin/openzeppeline-contracts@4.9.0

compiler:
  solc:
    version: 0.8.19
  remappings:
  - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.0"

networks:
  development:
    host: http://127.0.0.1:8545
    gas_limit: 12000000
    gas_price: 20000000000
    chainid: 1337
    
  ganache-local:
    host: http://127.0.0.1:7545
    gas_limit: 12000000
    gas_price: 20000000000
    chainid: 5777